const acronyms = {
	CDR: 'Call Detail Record',
	CRC: 'Cyclical Redundancy Check',
	DB: 'Database',
	DSC: 'Delivery Short Code',
	DSD: 'Data Set Download',
	DSDR: 'Data Set Download Response',
	DSS: 'Diagnostic System Services',
	DTE: 'Data Terminal Equipment',
	ECS: 'ETC Communications Subsstem',
	ETC: 'Earth Terminal Controller',
	FA: 'Field Application',
	GBS: 'Gateway Billing Subsystem',
	GEO: 'Geographical',
	GTE: 'Gateway Infrastructure Equipment',
	GSM: 'Global System for Mobile Communication',
	GSS: 'Gateway SBD Subsystem',
	GW: 'Gateway',
	IE: 'Information Element',
	IEI: 'Information Element Identifier',
	IMEI: 'International Mobile Equipment Identifier',
	IP: 'Internet Protocol',
	ISU: 'Iridium Subscriber Unit',
	LBT: 'L-Band Transceiver',
	MO: 'Mobile Originated',
	MOM: 'Mobile Originated Message',
	MOMSN: 'Mobile Originated Message Sequence Number',
	MT: 'Mobile Terminated',
	MTM: 'Mobile Terminated Message',
	MTMSN: 'Mobile Terminated Message Sequence Number',
	SBD: 'Short Burst Data',
	SEP: 'Short Burst Data ETC Processor',
	SPNet: 'Iridium Service Provider Network Provisioning Tool',
	SPP: 'Short Burst Data Post Processor',
	VA: 'Vendor Application',
};

export const getAcronymDefinition = (acronym: keyof typeof acronyms) => {
	return acronyms[acronym];
};
